export const SELECT_STATION = 'SELECT_STATION';
export const SELECT_STATION_ID = 'SELECT_STATION_ID';
export const SELECT_STATION_LINE = 'SELECT_STATION_LINE';
export const SET_STATION_DATA = 'SET_STATION_DATA';
